Mparmpakas Anastasios 

We start from tests of the algortithm. At th end is the algorithm with the same datasets trained with it.

In [1]:
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd 
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import sys
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestCentroid
from sklearn.metrics import f1_score
import string
from copy import copy, deepcopy

In [2]:
data = load_wine()
X = data.data
y = data.target

X_train_or, X_test_or, y_train_or, y_test_or = train_test_split(X, y, test_size=0.25, random_state=42)

In [3]:
clf = RandomForestClassifier(n_estimators=100, random_state=0)
clf.fit(X_train_or, y_train_or)

y_predict = clf.predict(X_test_or)

cf_matrix = confusion_matrix(y_test_or, y_predict)

print(cf_matrix)
print("=======================================")
print(classification_report(y_test_or, y_predict)) 
print(accuracy_score(y_test_or, y_predict)) 

[[15  0  0]
 [ 0 18  0]
 [ 0  0 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        12

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

1.0


In [4]:
y_test_or

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 1,
       2])

In [5]:
y_0 = np.copy(y)
y_0[y_0 == 0] = -1
y_0[y_0 != -1] = 0
y_0[y_0 == -1] = 1

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y_0, test_size=0.25, random_state=42)

In [7]:
y_test

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0])

In [8]:
clf1 = SVC(kernel='poly')
clf1.fit(X_train, y_train)

y_predict = clf1.predict(X_test)

cf_matrix = confusion_matrix(y_test, y_predict)

print(cf_matrix)
print("=======================================")
print(f1_score(y_test, y_predict)) 

[[30  0]
 [ 2 13]]
0.9285714285714286


In [9]:
X_train = np.delete(X_train_or, np.argwhere(y_train_or == 0).flatten(), axis=0)
X_test = np.delete(X_test_or, np.argwhere(y_test_or == 0).flatten(), axis=0)

y_train = np.delete(y_train_or, np.argwhere(y_train_or == 0).flatten())
y_test = np.delete(y_test_or, np.argwhere(y_test_or == 0).flatten())

In [10]:
y_train

array([1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2,
       2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1])

In [11]:
y_train[y_train == 1] = 0
y_train[y_train == 2] = 1
y_test[y_test == 1] = 0
y_test[y_test == 2] = 1

In [12]:
clf = SVC(kernel='linear')
clf.fit(X_train, y_train)

y_predict = clf.predict(X_test)

cf_matrix = confusion_matrix(y_test, y_predict)

print(cf_matrix)
print("=======================================")
print(classification_report(y_test, y_predict)) 

[[17  1]
 [ 0 12]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        18
           1       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [13]:
y_pred = []
for yl in X_test_or:
  if clf1.predict(yl.reshape(1, -1))[0] == 1:
    y_pred.append(0)
    continue
  else:
    if clf.predict(yl.reshape(1, -1))[0] == 1:
      y_pred.append(2)
      continue
    else:
      y_pred.append(1) 
      continue

In [14]:
y_pred = np.array(y_pred)

In [15]:
print(accuracy_score(y_test_or, y_pred)) 

0.9333333333333333


In [17]:
df=pd.read_excel("Date_Fruit_Datasets.xlsx")
df.head()

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0  422163   2378.908    837.8484    645.6693        0.6373  733.1539   
1  338136   2085.144    723.8198    595.2073        0.5690  656.1464   
2  526843   2647.394    940.7379    715.3638        0.6494  819.0222   
3  416063   2351.210    827.9804    645.2988        0.6266  727.8378   
4  347562   2160.354    763.9877    582.8359        0.6465  665.2291   

   SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  KurtosisRR  KurtosisRG  \
0    0.9947       424428  0.7831        1.2976  ...      3.2370      2.9574   
1    0.9974       339014  0.7795        1.2161  ...      2.6228      2.6350   
2    0.9962       528876  0.7657        1.3150  ...      3.7516      3.8611   
3    0.9948       418255  0.7759        1.2831  ...      5.0401      8.6136   
4    0.9908       350797  0.7569        1.3108  ...      2.7016      2.9761   

   KurtosisRB    EntropyRR    EntropyRG    EntropyRB  ALLdaub4RR  ALLdaub4RG  \
0      4.2287 -59191263232 -50714214400 -39922372608     58.7255     54.9554   
1      3.1704 -34233065472 -37462601728 -31477794816     50.0259     52.8168   
2      4.7192 -93948354560 -74738221056 -60311207936     65.4772     59.2860   
3      8.2618 -32074307584 -32060925952 -29575010304     43.3900     44.1259   
4      4.4146 -39980974080 -35980042240 -25593278464     52.7743     50.9080   

   ALLdaub4RB  Class  
0     47.8400  BERHI  
1     47.8315  BERHI  
2     51.9378  BERHI  
3     41.1882  BERHI  
4     42.6666  BERHI  

[5 rows x 35 columns]

In [18]:
df.shape

(898, 35)

In [19]:
X=df.drop(['Class'],axis=1)
y=df['Class']

In [20]:
y

0      BERHI
1      BERHI
2      BERHI
3      BERHI
4      BERHI
       ...  
893    SOGAY
894    SOGAY
895    SOGAY
896    SOGAY
897    SOGAY
Name: Class, Length: 898, dtype: object

In [21]:
myset = set(y)
print(myset)

{'BERHI', 'IRAQI', 'DOKOL', 'ROTANA', 'DEGLET', 'SAFAVI', 'SOGAY'}


In [22]:
y[y=='SOGAY'] = 0 
y[y=='IRAQI'] = 1 
y[y=='ROTANA'] = 2 
y[y=='BERHI'] = 3 
y[y=='DEGLET'] = 4 
y[y=='SAFAVI'] = 5 
y[y=='DOKOL'] = 6 
y=y.astype('int')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid 

In [23]:
X = np.array(X)
y = np.array(y)

In [24]:
X_train_or, X_test_or, y_train_or, y_test_or = train_test_split(X, y, test_size=0.25, random_state=42)

In [25]:
myset = set(y_train_or)
print(myset)

{0, 1, 2, 3, 4, 5, 6}


In [26]:
clf =  RandomForestClassifier(n_estimators=100, random_state=0)
clf.fit(X_train_or, y_train_or)

y_predict = clf.predict(X_test_or)

cf_matrix = confusion_matrix(y_test_or, y_predict)

print(cf_matrix)
print("=======================================")
print(accuracy_score(y_test_or, y_predict)) 

[[22  0  0  0  4  0  0]
 [ 0 12  0  1  0  0  0]
 [ 1  1 43  0  0  0  0]
 [ 1  2  0 12  0  0  0]
 [ 5  0  0  0 19  0  0]
 [ 0  0  0  0  0 42  0]
 [ 0  0  0  0  5  0 55]]
0.9111111111111111


In [27]:
y_test_or.shape

(225,)

In [28]:
y_0 = np.copy(y)
y_0[y_0 == 4] = -1
y_0[y_0 != -1] = 0
y_0[y_0 == -1] = 1

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y_0, test_size=0.25, random_state=42)

In [30]:
clf4 = RandomForestClassifier(random_state=4)
clf4.fit(X_train, y_train)

y_predict = clf4.predict(X_test)

cf_matrix = confusion_matrix(y_test, y_predict)

print(cf_matrix)
print("=======================================")
print(classification_report(y_test, y_predict)) 
print(accuracy_score(y_test, y_predict)) 

[[196   5]
 [  6  18]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       201
           1       0.78      0.75      0.77        24

    accuracy                           0.95       225
   macro avg       0.88      0.86      0.87       225
weighted avg       0.95      0.95      0.95       225

0.9511111111111111


In [31]:
X_train = np.delete(X_train_or, np.argwhere(y_train_or == 4).flatten(), axis=0)
X_test = np.delete(X_test_or, np.argwhere(y_test_or == 4).flatten(), axis=0)

y_train = np.delete(y_train_or, np.argwhere(y_train_or == 4).flatten())
y_test = np.delete(y_test_or, np.argwhere(y_test_or == 4).flatten())

In [32]:
y_train = np.copy(y_train)
y_train[y_train == 5] = -1
y_train[y_train != -1] = 0
y_train[y_train == -1] = 1

y_test = np.copy(y_test)
y_test[y_test == 5] = -1
y_test[y_test != -1] = 0
y_test[y_test == -1] = 1

In [33]:
clf5 = RandomForestClassifier(random_state=0)
clf5.fit(X_train, y_train)

y_predict = clf5.predict(X_test)

cf_matrix = confusion_matrix(y_test, y_predict)

print(cf_matrix)
print("=======================================")
print(classification_report(y_test, y_predict)) 
print(accuracy_score(y_test, y_predict)) 

[[159   0]
 [  0  42]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       159
           1       1.00      1.00      1.00        42

    accuracy                           1.00       201
   macro avg       1.00      1.00      1.00       201
weighted avg       1.00      1.00      1.00       201

1.0


In [34]:
X_train = np.delete(X_train_or, np.argwhere(y_train_or == 5).flatten(), axis=0)
X_test = np.delete(X_test_or, np.argwhere(y_test_or == 5).flatten(), axis=0)

y_train = np.delete(y_train_or, np.argwhere(y_train_or == 5).flatten())
y_test = np.delete(y_test_or, np.argwhere(y_test_or == 5).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 4).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 4).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 4).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 4).flatten())

In [35]:
y_test

array([6, 6, 0, 3, 6, 1, 6, 6, 6, 6, 6, 2, 2, 0, 0, 2, 6, 2, 6, 3, 0, 3,
       0, 6, 2, 6, 3, 6, 6, 2, 6, 6, 6, 2, 1, 6, 0, 6, 2, 6, 6, 3, 1, 0,
       6, 6, 6, 0, 6, 2, 2, 6, 6, 2, 0, 1, 2, 6, 2, 2, 6, 2, 2, 6, 2, 6,
       1, 6, 6, 1, 6, 6, 6, 6, 2, 2, 1, 6, 2, 1, 2, 2, 6, 6, 2, 2, 2, 0,
       2, 2, 6, 0, 2, 2, 6, 1, 2, 2, 6, 2, 6, 3, 0, 0, 6, 3, 3, 0, 2, 0,
       0, 6, 1, 6, 0, 3, 3, 6, 2, 6, 2, 0, 0, 0, 3, 3, 6, 0, 6, 1, 1, 6,
       3, 3, 2, 6, 6, 2, 2, 2, 2, 0, 0, 2, 6, 2, 2, 6, 2, 0, 0, 6, 3, 2,
       1, 6, 0, 6, 6])

In [36]:
y_train = np.copy(y_train)
y_train[y_train == 0] = -1
y_train[y_train != -1] = 0
y_train[y_train == -1] = 1

y_test = np.copy(y_test)
y_test[y_test == 0] = -1
y_test[y_test != -1] = 0
y_test[y_test == -1] = 1

In [37]:
clf0 = RandomForestClassifier(random_state=3)
clf0.fit(X_train, y_train)

y_predict = clf0.predict(X_test)

cf_matrix = confusion_matrix(y_test, y_predict)

print(cf_matrix)
print("=======================================")
print(classification_report(y_test, y_predict)) 
print(accuracy_score(y_test, y_predict)) 

[[129   4]
 [  1  25]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       133
           1       0.86      0.96      0.91        26

    accuracy                           0.97       159
   macro avg       0.93      0.97      0.95       159
weighted avg       0.97      0.97      0.97       159

0.9685534591194969


In [38]:
X_train = np.delete(X_train_or, np.argwhere(y_train_or == 5).flatten(), axis=0)
X_test = np.delete(X_test_or, np.argwhere(y_test_or == 5).flatten(), axis=0)

y_train = np.delete(y_train_or, np.argwhere(y_train_or == 5).flatten())
y_test = np.delete(y_test_or, np.argwhere(y_test_or == 5).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 4).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 4).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 4).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 4).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 0).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 0).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 0).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 0).flatten())

In [39]:
y_test

array([6, 6, 3, 6, 1, 6, 6, 6, 6, 6, 2, 2, 2, 6, 2, 6, 3, 3, 6, 2, 6, 3,
       6, 6, 2, 6, 6, 6, 2, 1, 6, 6, 2, 6, 6, 3, 1, 6, 6, 6, 6, 2, 2, 6,
       6, 2, 1, 2, 6, 2, 2, 6, 2, 2, 6, 2, 6, 1, 6, 6, 1, 6, 6, 6, 6, 2,
       2, 1, 6, 2, 1, 2, 2, 6, 6, 2, 2, 2, 2, 2, 6, 2, 2, 6, 1, 2, 2, 6,
       2, 6, 3, 6, 3, 3, 2, 6, 1, 6, 3, 3, 6, 2, 6, 2, 3, 3, 6, 6, 1, 1,
       6, 3, 3, 2, 6, 6, 2, 2, 2, 2, 2, 6, 2, 2, 6, 2, 6, 3, 2, 1, 6, 6,
       6])

In [40]:
y_train = np.copy(y_train)
y_train[y_train == 3] = -1
y_train[y_train != -1] = 0
y_train[y_train == -1] = 1

y_test = np.copy(y_test)
y_test[y_test == 3] = -1
y_test[y_test != -1] = 0
y_test[y_test == -1] = 1

In [41]:
clf3 = RandomForestClassifier(random_state=3)
clf3.fit(X_train, y_train)

y_predict = clf3.predict(X_test)

cf_matrix = confusion_matrix(y_test, y_predict)

print(cf_matrix)
print("=======================================")
print(classification_report(y_test, y_predict)) 
print(accuracy_score(y_test, y_predict)) 

[[118   0]
 [  5  10]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       118
           1       1.00      0.67      0.80        15

    accuracy                           0.96       133
   macro avg       0.98      0.83      0.89       133
weighted avg       0.96      0.96      0.96       133

0.9624060150375939


In [47]:
X_train = np.delete(X_train_or, np.argwhere(y_train_or == 5).flatten(), axis=0)
X_test = np.delete(X_test_or, np.argwhere(y_test_or == 5).flatten(), axis=0)

y_train = np.delete(y_train_or, np.argwhere(y_train_or == 5).flatten())
y_test = np.delete(y_test_or, np.argwhere(y_test_or == 5).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 4).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 4).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 4).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 4).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 0).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 0).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 0).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 0).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 3).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 3).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 3).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 3).flatten())

In [48]:
y_test

array([6, 6, 6, 1, 6, 6, 6, 6, 6, 2, 2, 2, 6, 2, 6, 6, 2, 6, 6, 6, 2, 6,
       6, 6, 2, 1, 6, 6, 2, 6, 6, 1, 6, 6, 6, 6, 2, 2, 6, 6, 2, 1, 2, 6,
       2, 2, 6, 2, 2, 6, 2, 6, 1, 6, 6, 1, 6, 6, 6, 6, 2, 2, 1, 6, 2, 1,
       2, 2, 6, 6, 2, 2, 2, 2, 2, 6, 2, 2, 6, 1, 2, 2, 6, 2, 6, 6, 2, 6,
       1, 6, 6, 2, 6, 2, 6, 6, 1, 1, 6, 2, 6, 6, 2, 2, 2, 2, 2, 6, 2, 2,
       6, 2, 6, 2, 1, 6, 6, 6])

In [49]:
y_train = np.copy(y_train)
y_train[y_train == 1] = -1
y_train[y_train != -1] = 0
y_train[y_train == -1] = 1

y_test = np.copy(y_test)
y_test[y_test == 1] = -1
y_test[y_test != -1] = 0
y_test[y_test == -1] = 1

In [50]:
clf1 = LinearDiscriminantAnalysis()
clf1.fit(X_train, y_train)

y_predict = clf1.predict(X_test)

cf_matrix = confusion_matrix(y_test, y_predict)

print(cf_matrix)
print("=======================================")
print(classification_report(y_test, y_predict)) 
print(accuracy_score(y_test, y_predict)) 

[[105   0]
 [  0  13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
           1       1.00      1.00      1.00        13

    accuracy                           1.00       118
   macro avg       1.00      1.00      1.00       118
weighted avg       1.00      1.00      1.00       118

1.0


In [51]:
X_train = np.delete(X_train_or, np.argwhere(y_train_or == 5).flatten(), axis=0)
X_test = np.delete(X_test_or, np.argwhere(y_test_or == 5).flatten(), axis=0)

y_train = np.delete(y_train_or, np.argwhere(y_train_or == 5).flatten())
y_test = np.delete(y_test_or, np.argwhere(y_test_or == 5).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 0).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 0).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 0).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 0).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 1).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 1).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 1).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 1).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 3).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 3).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 3).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 3).flatten())

X_train = np.delete(X_train, np.argwhere(y_train == 4).flatten(), axis=0)
X_test = np.delete(X_test, np.argwhere(y_test == 4).flatten(), axis=0)

y_train = np.delete(y_train, np.argwhere(y_train == 4).flatten())
y_test = np.delete(y_test, np.argwhere(y_test == 4).flatten())

In [52]:
y_test

array([6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 2, 6, 6, 2, 6, 6, 6, 2, 6, 6,
       6, 2, 6, 6, 2, 6, 6, 6, 6, 6, 6, 2, 2, 6, 6, 2, 2, 6, 2, 2, 6, 2,
       2, 6, 2, 6, 6, 6, 6, 6, 6, 6, 2, 2, 6, 2, 2, 2, 6, 6, 2, 2, 2, 2,
       2, 6, 2, 2, 6, 2, 2, 6, 2, 6, 6, 2, 6, 6, 6, 2, 6, 2, 6, 6, 6, 2,
       6, 6, 2, 2, 2, 2, 2, 6, 2, 2, 6, 2, 6, 2, 6, 6, 6])

In [53]:
clf_last = LinearDiscriminantAnalysis()
clf_last.fit(X_train, y_train)

y_predict = clf_last.predict(X_test)

cf_matrix = confusion_matrix(y_test, y_predict)

print(cf_matrix)
print("=======================================")
print(classification_report(y_test, y_predict)) 
print(accuracy_score(y_test, y_predict)) 

[[45  0]
 [ 0 60]]
              precision    recall  f1-score   support

           2       1.00      1.00      1.00        45
           6       1.00      1.00      1.00        60

    accuracy                           1.00       105
   macro avg       1.00      1.00      1.00       105
weighted avg       1.00      1.00      1.00       105

1.0


In [54]:
clf_last.predict(X_test[3].reshape(1, -1))

array([6])

In [55]:
y_pred = []
for yl in X_test_or:
  if clf4.predict(yl.reshape(1, -1))[0] == 1:
    y_pred.append(4)
    continue
  else:
    if clf5.predict(yl.reshape(1, -1))[0] == 1:
      y_pred.append(5)
      continue
    else: 
      if clf0.predict(yl.reshape(1, -1))[0] == 1:
        y_pred.append(0)
        continue
      else:
        if clf3.predict(yl.reshape(1, -1))[0] == 1:
          y_pred.append(3)
          continue      
        else:
          if clf1.predict(yl.reshape(1, -1))[0] == 1:
            y_pred.append(1)
            continue
          else:
            y_pred.append(clf_last.predict(yl.reshape(1, -1))[0])
            continue

In [56]:
y_pred = np.array(y_pred)

In [57]:
print(accuracy_score(y_test_or, y_pred)) 

0.9111111111111111


The Algorithm


Methods: highestF1 imbalance

In [65]:
class MultipleSimplificationLearner():

  def __init__(self, classifiers: list, mode: string) -> None:
    self.classifiers = classifiers
    self.mode = mode
    self.models = []
    self.ycls = set(y)
    self.X_train = np.array([]) 
    self.X_test = np.array([])
    self.y_train = np.array([]) 
    self.y_test = np.array([])
    self.classifier_list = []
    self.class_list = []

  def one_vs_rest(self, ycl: int, y_train, y_test):
    y_train_0 = np.copy(y_train)
    y_train_0[y_train_0 == ycl] = -1
    y_train_0[y_train_0 != -1] = 0
    y_train_0[y_train_0 == -1] = 1

    y_test_0 = np.copy(y_test)
    y_test_0[y_test_0 == ycl] = -1
    y_test_0[y_test_0 != -1] = 0
    y_test_0[y_test_0 == -1] = 1

    return y_train_0, y_test_0

  def remove_classes(self, cls: list, X_train, X_test, y_train, y_test):
    X_train_0 = np.copy(X_train)
    X_test_0 = np.copy(X_test)
    y_train_0 = np.copy(y_train)
    y_test_0 = np.copy(y_test)

    for cl in cls:
      X_train_0 = np.delete(X_train_0, np.argwhere(y_train_0 == cl).flatten(), axis=0)
      X_test_0 = np.delete(X_test_0, np.argwhere(y_test_0 == cl).flatten(), axis=0)

      y_train_0 = np.delete(y_train_0, np.argwhere(y_train_0 == cl).flatten())
      y_test_0 = np.delete(y_test_0, np.argwhere(y_test_0 == cl).flatten())

    return X_train_0, X_test_0, y_train_0, y_test_0


  def fit(self, X: np.ndarray, y: np.ndarray):
  
    self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size=0.25, random_state=42)

    self.models = []

    self.ycls = set(y)
    
    if self.mode == "highestF1":
      return self.highestF1_fit()
    if self.mode == "imbalance":
      return self.imbalance_fit()

    print("Wrong method!")

  def imbalance_fit(self):

    count_ycl = 0
    acc = 0.0

    X_train_0 = self.X_train
    X_test_0 = self.X_test
    y_train_0 = self.y_train
    y_test_0 = self.y_test

    ycls = self.ycls.copy()


    while len(ycls) > 2:

      X_train, X_test, y_train, y_test = self.remove_classes(self.class_list, X_train_0, X_test_0, y_train_0, y_test_0)

      for ycl in ycls:

        if count_ycl <  np.count_nonzero(y_train == ycl) + np.count_nonzero(y_test == ycl):
          count_ycl = np.count_nonzero(y_train == ycl) + np.count_nonzero(y_test == ycl)
          ycln = ycl

      count_ycl = 0

      for classifier in self.classifiers:
        if acc == 1.0:
          break
        current_classifier = deepcopy(classifier)
        current_classifier.fit(X_train, y_train)
        y_predict = current_classifier.predict(X_test)
        accscore = f1_score(y_test, y_predict,pos_label= min(y_test))

        if acc < accscore:
          acc = accscore
          cl = current_classifier
          ycln = ycl

      ycls.remove(ycln)
      acc = 0.0 
      self.classifier_list.append(cl)
      self.class_list.append(ycln)



    X_train, X_test, y_train, y_test = self.remove_classes(self.class_list, X_train_0, X_test_0, y_train_0, y_test_0)
  
    for classifier in self.classifiers:
      current_classifier = deepcopy(classifier)

      current_classifier.fit(X_train, y_train)
      y_predict = current_classifier.predict(X_test)

      accscore = f1_score(y_test, y_predict,pos_label= min(y_test))

      if acc < accscore:
        acc = accscore
        cl = current_classifier

    self.classifier_list.append(cl)

    return 


  def highestF1_fit(self):

    acc = 0.0

    X_train_0 = self.X_train
    X_test_0 = self.X_test
    y_train_0 = self.y_train
    y_test_0 = self.y_test

    ycls = self.ycls.copy()

    while len(ycls) > 2:

      for ycl in ycls:

        X_train, X_test, y_train, y_test = self.remove_classes(self.class_list, X_train_0, X_test_0, y_train_0, y_test_0)

        y_train, y_test = self.one_vs_rest(ycl, y_train, y_test)
      
        for classifier in self.classifiers:
          if acc == 1.0:
            break
          current_classifier = deepcopy(classifier)
          current_classifier.fit(X_train, y_train)
          y_predict = current_classifier.predict(X_test)
          accscore = f1_score(y_test, y_predict,pos_label= min(y_test))

          if acc < accscore:
            acc = accscore
            cl = current_classifier
            ycln = ycl
          
 
      ycls.remove(ycln)
      acc = 0.0 
      self.classifier_list.append(cl)
      self.class_list.append(ycln)

    X_train, X_test, y_train, y_test = self.remove_classes(self.class_list, X_train_0, X_test_0, y_train_0, y_test_0)
    
    for classifier in self.classifiers:
      current_classifier = deepcopy(classifier)

      current_classifier.fit(X_train, y_train)
      y_predict = current_classifier.predict(X_test)

      accscore = f1_score(y_test, y_predict, pos_label= min(y_test))

      if acc < accscore:
        acc = accscore
        cl = current_classifier

    self.classifier_list.append(cl)

    return

 
  def predict(self, X_pred: np.ndarray):
    y_pred = []

    cont = 0
    for x_p in X_pred:

      for cln in range(len(self.classifier_list)-1):
        pred = self.classifier_list[cln].predict(x_p.reshape(1, -1))
        if pred == 1:
          y_pred.append(self.class_list[cln])
          cont = 1
          break

      if cont == 0:
        pred = self.classifier_list[-1].predict(x_p.reshape(1, -1))[0]
        y_pred.append(pred)
      cont = 0
    return np.array(y_pred)




In [66]:
classifiers = [SVC(kernel='poly'),
               RandomForestClassifier(n_estimators=100, random_state=0), 
               GaussianNB()]

Wine

In [67]:
data = load_wine()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [68]:
model = MultipleSimplificationLearner(classifiers,"highestF1")

model.fit(X, y)

y_pred = model.predict(X_test)


print((y_pred))
print((y_test))
print(accuracy_score(y_test, y_pred)) 

[0 0 2 0 1 0 1 2 1 2 0 2 0 1 0 1 1 1 0 1 0 1 1 2 2 2 1 1 1 0 0 1 2 0 0 0 2
 2 1 2 0 1 1 1 2]
[0 0 2 0 1 0 1 2 1 2 0 2 0 1 0 1 1 1 0 1 0 1 1 2 2 2 1 1 1 0 0 1 2 0 0 0 2
 2 1 2 0 1 1 1 2]
1.0


Date Fruit

In [69]:
df=pd.read_excel("Date_Fruit_Datasets.xlsx")
df.head()

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0  422163   2378.908    837.8484    645.6693        0.6373  733.1539   
1  338136   2085.144    723.8198    595.2073        0.5690  656.1464   
2  526843   2647.394    940.7379    715.3638        0.6494  819.0222   
3  416063   2351.210    827.9804    645.2988        0.6266  727.8378   
4  347562   2160.354    763.9877    582.8359        0.6465  665.2291   

   SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  KurtosisRR  KurtosisRG  \
0    0.9947       424428  0.7831        1.2976  ...      3.2370      2.9574   
1    0.9974       339014  0.7795        1.2161  ...      2.6228      2.6350   
2    0.9962       528876  0.7657        1.3150  ...      3.7516      3.8611   
3    0.9948       418255  0.7759        1.2831  ...      5.0401      8.6136   
4    0.9908       350797  0.7569        1.3108  ...      2.7016      2.9761   

   KurtosisRB    EntropyRR    EntropyRG    EntropyRB  ALLdaub4RR  ALLdaub4RG  \
0      4.2287 -59191263232 -50714214400 -39922372608     58.7255     54.9554   
1      3.1704 -34233065472 -37462601728 -31477794816     50.0259     52.8168   
2      4.7192 -93948354560 -74738221056 -60311207936     65.4772     59.2860   
3      8.2618 -32074307584 -32060925952 -29575010304     43.3900     44.1259   
4      4.4146 -39980974080 -35980042240 -25593278464     52.7743     50.9080   

   ALLdaub4RB  Class  
0     47.8400  BERHI  
1     47.8315  BERHI  
2     51.9378  BERHI  
3     41.1882  BERHI  
4     42.6666  BERHI  

[5 rows x 35 columns]

In [70]:
X=df.drop(['Class'],axis=1)
y=df['Class']

myset = set(y)
y[y=='SOGAY'] = 0 
y[y=='IRAQI'] = 1 
y[y=='ROTANA'] = 2 
y[y=='BERHI'] = 3 
y[y=='DEGLET'] = 4 
y[y=='SAFAVI'] = 5 
y[y=='DOKOL'] = 6 
y=y.astype('int')

X = np.array(X)
y = np.array(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A va

In [71]:
classifiers = [LinearDiscriminantAnalysis(),
               SVC(kernel='poly'),
               RandomForestClassifier(n_estimators=100, random_state=0), 
               GaussianNB()]

model = MultipleSimplificationLearner(classifiers,"highestF1")

model.fit(X, y)

y_pred = model.predict(X_test)

print(accuracy_score(y_test, y_pred)) 

0.92
